name: staging-react-build-and-deploy

env:
  REACT_APP_ENDPOINT: ${{ secrets.REACT_APP_ENDPOINT }}

on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'staging'

jobs:
  Build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checking out code
        uses: actions/checkout@v3

      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installing dependencies
        run: npm install

      - name: Building project
        run: npm run build
        env:
          CI: false

      - name: Share build inside workflow
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: build

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    environment:
      name: Staging
      url: 'https://the-spot.s3.amazonaws.com/index.html'

    steps:
      - name: Get build
        uses: actions/download-artifact@v3
        with:
          name: react-build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy to S3
        run: aws s3 sync . s3://the-spot
